[phases.setup]
nixPkgs = ['maven', 'jdk21']

[phases.build]
cmds = ['chmod +x mvnw', './mvnw clean install -DskipTests']

[start]
cmd = 'java -Dserver.port=$PORT -jar target/mindora-backend-1.0.0.jar'

